In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,3,4])
type(s)

pandas.Series

In [ ]:
s1=pd.Series([1,2,3,4],index=["A","B","C","D"])
s1

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
data = [[1,444,"adc"],
        [2,555,"def"],
        [1,666,"ghi"],
        [1,444,"xyz"],
        ]

data_2 ={"ID":[1,2,3,4],
         "Std_id_dict":[444,555,666,444],
         "Dept":['abc','def','ghi','xyz']
    }

df = pd.DataFrame(data,columns=["ID","Std_id","Dept"])
df

df = pd.DataFrame(data_2)
display(df)

   ID  Std_id_dict Dept
0   1          444  abc
1   2          555  def
2   3          666  ghi
3   4          444  xyz

In [ ]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz'],
        ]

df = pd.DataFrame(data,columns=["ID","Std_id","Dept"])
df

   ID  Std_id Dept
0   1     444  abc
1   2     555  def
2   3     666  ghi
3   4     444  xyz

In [ ]:
df.columns

Index(['ID', 'Std_id', 'Dept'], dtype='str')

In [ ]:
index =['row1','row2','row3','row4']
df.index = index
df

      ID  Std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [ ]:
df.dtypes

ID        int64
Std_id    int64
Dept        str
dtype: object

In [ ]:
df['Dept'].dtype

In [ ]:
df['Dept']= df['Dept'].astype("category")
df['Dept'].dtype

CategoricalDtype(categories=['abc', 'def', 'ghi', 'xyz'], ordered=False, categories_dtype=str)

In [ ]:
df.dtypes

ID           int64
Std_id       int64
Dept      category
dtype: object

In [ ]:
# EDA
df.head()

      ID  Std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [ ]:
df.tail(2)

      ID  Std_id Dept
row3   3     666  ghi
row4   4     444  xyz

In [ ]:
df.describe()
df.describe(include="category")

       Dept
count     4
unique    4
top     abc
freq      1

In [ ]:
x=df["Std_id"].unique().sum()
x

np.int64(1665)

In [ ]:
df["Std_id"].min()

np.int64(444)

In [ ]:
df.Dept.idxmax()
df.Dept.idxmin()

'row1'

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4 non-null      int64
 1   Std_id  4 non-null      int64
 2   Dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 304.0+ bytes

In [ ]:
df['Dept'].value_counts()

Dept
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [ ]:
df['ID'].sum()

np.int64(10)

In [ ]:
# Data Manipulation:

def duplicate(x):
    return x * 2

df["Std_id"].apply(duplicate)
df["Std_id"].apply(lambda x: x*2)

row1     888
row2    1110
row3    1332
row4     888
Name: Std_id, dtype: int64

In [ ]:
# Slicing Data:
df['Dept'].iloc[3]

'xyz'

In [ ]:
df.iloc[2,1]

np.int64(666)

In [ ]:
df.Dept.iloc[0:2]

row1    abc
row2    def
Name: Dept, dtype: category
Categories (4, str): ['abc', 'def', 'ghi', 'xyz']

In [ ]:
num_col = df.iloc[:,0:-1]
cat_col = df.iloc[:,-1:]
num_col

      ID  Std_id
row1   1     444
row2   2     555
row3   3     666
row4   4     444

In [ ]:
cat_col

     Dept
row1  abc
row2  def
row3  ghi
row4  xyz

In [ ]:
new_col = df.Std_id + df.ID
new_col

row1    445
row2    557
row3    669
row4    448
dtype: int64

In [ ]:
df["new_col"]= df.Std_id + df.ID
df

      ID  Std_id Dept  new_col
row1   1     444  abc      445
row2   2     555  def      557
row3   3     666  ghi      669
row4   4     444  xyz      448

In [ ]:
df.drop("new_col", axis=1)

      ID  Std_id Dept
row1   1     444  abc
row2   2     555  def
row3   3     666  ghi
row4   4     444  xyz

In [ ]:
df.drop("row2", axis=0)

      ID  Std_id Dept  new_col
row1   1     444  abc      445
row3   3     666  ghi      669
row4   4     444  xyz      448

In [ ]:
df.drop(["row2","row3"], axis=0)

      ID  Std_id Dept  new_col
row1   1     444  abc      445
row4   4     444  xyz      448

In [ ]:
df.isnull().sum()

ID         0
Std_id     0
Dept       0
new_col    0
dtype: int64

In [ ]:
import numpy as np

In [ ]:
data = [[1,444,"adc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,np.nan,"xyz"],
        ]

df = pd.DataFrame(data,columns=["ID","Std_id","Dept"])
df

   ID  Std_id Dept
0   1   444.0  adc
1   2   555.0  def
2   3   666.0  ghi
3   4     NaN  xyz

In [ ]:
null = df.isnull().sum()
pd.DataFrame(null).T

   ID  Std_id  Dept
0   0       1     0

In [ ]:
def isNUll(df):
    null = df.isnull().sum()  
    return pd.DataFrame(null).T

In [ ]:
isNUll(df)

   ID  Std_id  Dept
0   0       1     0